// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkqyjIIFRub-SeToBhI-m2htTw3qqvI9k',
    appId: '1:451692864119:web:fa9bac4eb0f82b44309c72',
    messagingSenderId: '451692864119',
    projectId: 'mudratechnologies-a96c0',
    authDomain: 'mudratechnologies-a96c0.firebaseapp.com',
    storageBucket: 'mudratechnologies-a96c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhACaxFoHx54qtUIZlT6D4HDIumvTU8Xg',
    appId: '1:451692864119:android:61242ab94835b67c309c72',
    messagingSenderId: '451692864119',
    projectId: 'mudratechnologies-a96c0',
    storageBucket: 'mudratechnologies-a96c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIl_AOWHVgnAiOiUU-q_jpyMu3ttOeaak',
    appId: '1:451692864119:ios:af81c0970bfe1d5a309c72',
    messagingSenderId: '451692864119',
    projectId: 'mudratechnologies-a96c0',
    storageBucket: 'mudratechnologies-a96c0.appspot.com',
    iosBundleId: 'com.example.mudratechnologies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIl_AOWHVgnAiOiUU-q_jpyMu3ttOeaak',
    appId: '1:451692864119:ios:af81c0970bfe1d5a309c72',
    messagingSenderId: '451692864119',
    projectId: 'mudratechnologies-a96c0',
    storageBucket: 'mudratechnologies-a96c0.appspot.com',
    iosBundleId: 'com.example.mudratechnologies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkqyjIIFRub-SeToBhI-m2htTw3qqvI9k',
    appId: '1:451692864119:web:642f92035af14434309c72',
    messagingSenderId: '451692864119',
    projectId: 'mudratechnologies-a96c0',
    authDomain: 'mudratechnologies-a96c0.firebaseapp.com',
    storageBucket: 'mudratechnologies-a96c0.appspot.com',
  );
}
